In [1]:
from tensorflow.keras.preprocessing import text
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
import numpy as np

In [2]:
sentence = '아이유 콘서트 매진되었어요. 어쩔티비'
result = text.text_to_word_sequence(sentence)
print(sentence)
print(result)

아이유 콘서트 매진되었어요. 어쩔티비
['아이유', '콘서트', '매진되었어요', '어쩔티비']


In [3]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

In [4]:
# 토큰화 문장에 list
token = text.Tokenizer()
token.fit_on_texts(docs)

In [5]:
print('단어 카운트\n', token.word_counts) 
# OrderedDict 순서가 있는 딕셔너리

단어 카운트
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [6]:
print('각 단어가 몇 개의 문장에 포함되어 있는가\n', token.word_docs) 

각 단어가 몇 개의 문장에 포함되어 있는가
 defaultdict(<class 'int'>, {'합니다': 1, '토큰화': 1, '단어를': 1, '각': 1, '텍스트의': 2, '먼저': 1, '나누어': 1, '딥러닝에서': 2, '단어로': 1, '인식됩니다': 1, '토큰화해야': 1, '있습니다': 1, '수': 1, '결과는': 1, '사용할': 1, '토큰화한': 1})


In [7]:
print('각 단어에 매겨진 인덱스\n', token.word_index) 
#index 자주 출몰하는 단어가 우선순위로 매겨진다.
# 단어의 index는 1부터 시작한다.

각 단어에 매겨진 인덱스
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [8]:
text1 = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"
token = text.Tokenizer()
token.fit_on_texts([text1])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


 String으로 된 데이터를 수치데이터로 변형

In [9]:
x = token.texts_to_sequences([text1])
print(x) 

[[1, 2, 3, 4, 5, 6]]


In [10]:
from tensorflow.keras.utils import to_categorical

# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
# 단어 인덱스 1부터 시작 맨 앞에는 비워두어야하기 때문
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [11]:
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요",
        "추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요",
        "생각보다 지루하네요","연기가 어색해요","재미없어요"]

In [12]:
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [13]:
token = text.Tokenizer()
token.fit_on_texts(docs)
print(token.word_index) # 토큰화된 결과를 출력해 확인합니다.

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [14]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n", x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [15]:
padded_x = pad_sequences(x, 4) # 서로 다른 길이의 데이터를 4로 맞추기
#4보다 많으면 자르고 적은 것은 채워진다.
print("패딩 결과:\n", padded_x)

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [16]:
word_size = len(token.word_index) + 1 
# 단어가 1부터 시작

model = Sequential()
model.add(layers.Embedding(word_size, 8, input_length=4)) #8차원으로 만들겠다.
model.add(layers.Flatten())
model.add(layers.Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              168       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer='adam', loss='binary_crossentropy',
              metrics=['accuracy'])

In [18]:
model.fit(padded_x, classes, epochs=40)

Epoch 1/40
1/1 [==============================] - 0s 2ms/step - loss: 0.6857 - accuracy: 0.6000
Epoch 2/40
1/1 [==============================] - 0s 4ms/step - loss: 0.6833 - accuracy: 0.7000
Epoch 3/40
1/1 [==============================] - 0s 2ms/step - loss: 0.6808 - accuracy: 0.7000
Epoch 4/40
1/1 [==============================] - 0s 996us/step - loss: 0.6784 - accuracy: 0.8000
Epoch 5/40
1/1 [==============================] - 0s 2ms/step - loss: 0.6759 - accuracy: 0.8000
Epoch 6/40
1/1 [==============================] - 0s 3ms/step - loss: 0.6735 - accuracy: 0.8000
Epoch 7/40
1/1 [==============================] - 0s 2ms/step - loss: 0.6710 - accuracy: 0.8000
Epoch 8/40
1/1 [==============================] - 0s 998us/step - loss: 0.6685 - accuracy: 0.8000
Epoch 9/40
1/1 [==============================] - 0s 3ms/step - loss: 0.6661 - accuracy: 0.8000
Epoch 10/40
1/1 [==============================] - 0s 998us/step - loss: 0.6636 - accuracy: 0.9000
Epoch 11/40
1/1 [================

In [20]:
print("\n Test Accuracy: " , model.evaluate(padded_x, classes)[1])

1/1 [==============================] - 0s 997us/step - loss: 0.5838 - accuracy: 0.9000

 Test Accuracy:  0.8999999761581421
